#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$url = $argv[1];
$path = isset($argv[2]) && $argv[2] === '-o' ? $argv[3] : __DIR__;

$loader = new App\PageLoader();
$path = $loader->load($url, $path);
echo $path;